### ISSUE TITLE
Horse Menu

### ISSUE THREAD

**Issue by NeonOdyssey** [Unchained-RP/bugs#7]
whenever i try and access my horse the menu closes
like the saddle bags

From > Zerota#9803

**Comment by NeonOdyssey** [comment]
^ with this i had some problem but only with his horse
He has 30 wood in his bag and some sticks, he tried to go in it and it closed out of it straight away, he transferred the ownership to me and i had some problem.

From > Lucy O'Conner ♡ | Luceh#6969

**Comment by NeonOdyssey** [comment]
I’ve been having the same issue. It’s been brought to staff’s attention, but so far it seems only you and I are encountering the problem

From > Moon Crane | Haytham Martin | Aichios#9902

**Comment by NeonOdyssey** [comment]
i played a bit earlier and had no issues but i just got on there again and it is happening again

From > Zerota#9803

**Comment by LokidPhoenix** [comment]
for all who have this error... 
Try to change your RedM to the canary version!
I had this errors yesterday too, but since i switched to the canary version, the errors are gone!

If you don't know, how to switch to canary! here is an description:

_You can use the Canary version by going to your RedM directory 
locating the CitizenFX.ini file and adding the line UpdateChannel=canary.
when the line UpdateCannel=beta exists, just exchange the word beta with canary.
Save the file and start RedM._ 
Ingame you should now see, that you are playing on the canary version.

**Comment by NeonOdyssey** [comment]
> for all who have this error... Try to change your RedM to the canary version! I had this errors yesterday too, but since i switched to the canary version, the errors are gone!
> 
> If you don't know, how to switch to canary! here is an description:
> 
> _You can use the Canary version by going to your RedM directory locating the CitizenFX.ini file and adding the line UpdateChannel=canary. when the line UpdateCannel=beta exists, just exchange the word beta with canary. Save the file and start RedM._ Ingame you should now see, that you are playing on the canary version.

Thanks for your reply, if anyone has any issues please re-open this issue
